
# Rate limiting configuration
requests_per_second = 10
burst = 5

# Retry limit
retry_limit = 3

send_batch_directly = true

# List of all providers
providers = [
  'https://rpc.ankr.com/polygon',
  'https://polygon-rpc.com',
  'https://polygon.llamarpc.com',
  'https://polygon.blockpi.network/v1/rpc/public',
  'https://matic-mainnet.chainstacklabs.com',
  'https://polygon-mainnet.public.blastapi.io',
  'https://polygon-bor.publicnode.com',
  'https://poly-rpc.gateway.pokt.network',
  'https://polygon.rpc.blxrbdn.com',
  'https://polygon-mainnet.g.alchemy.com/v2/demo',
  'https://rpc-mainnet.matic.quiknode.pro',
  'https://api.zan.top/node/v1/polygon/mainnet/public',
  'https://gateway.tenderly.co/public/polygon',
  'https://polygon.gateway.tenderly.co',
  'https://polygon.meowrpc.com',
  'https://1rpc.io/matic',
  'https://endpoints.omniatech.io/v1/matic/mainnet/public',
  'https://rpc-mainnet.maticvigil.com',
  'https://polygon.drpc.org'
]

# Mapping of methods to providers
[[methods_mapping]]
  method =  'trace_block'
  providers = [
    'https://polygon-rpc.com',
    'https://rpc.ankr.com/polygon', 
    'https://polygon.llamarpc.com',
    'https://polygon.blockpi.network/v1/rpc/public'
  ]
 
[[methods_mapping]]
  method =  'trace_transaction'
  providers = [
    "https://polygon-rpc.com'",
    "https://rpc.ankr.com/polygon", 
    "https://polygon.llamarpc.com",
    "https://polygon.blockpi.network/v1/rpc/public"
  ]

