
# Rate limiting configuration
requests_per_second = 50
burst = 5

# Retry limit
retry_limit = 10

send_batch_directly = true

# List of all providers
providers = [
  'https://polygon-mainnet.g.alchemy.com/v2/A3V1zvAQ-n6ENhmdGFnz9EvCfgVaddhg',
  'https://rpc.ankr.com/polygon',
  'https://polygon-rpc.com',
  'https://polygon.llamarpc.com',
  'https://polygon.blockpi.network/v1/rpc/public'
]

# Mapping of methods to providers
[[methods_mapping]]
  method =  'trace_block'
  providers = [
    'https://polygon-rpc.com',
    'https://rpc.ankr.com/polygon', 
    'https://polygon.llamarpc.com',
    'https://polygon.blockpi.network/v1/rpc/public'
  ]
 
[[methods_mapping]]
  method =  'eth_getBlockReceipts'
  providers = [
    'https://polygon-rpc.com',
    'https://rpc.ankr.com/polygon', 
  ]
